#!/bin/bash

# Script to remove AI contributors from git history
# WARNING: This rewrites history - use with caution!

echo "🧹 Cleaning AI Contributors from Git History"
echo "============================================"
echo ""
echo "⚠️  WARNING: This will rewrite git history!"
echo "   Make sure all team members are aware before proceeding."
echo ""
read -p "Are you sure you want to continue? (y/N): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted."
    exit 1
fi

echo ""
echo "📊 Current contributors with AI:"
git shortlog -sne | grep -iE "(Claude|Copilot|anthropic|bot)" || echo "None found in shortlog"

echo ""
echo "🔍 Searching for AI co-authors in commit messages..."
COMMITS_WITH_AI=$(git log --all --format='%H' --grep="Co-[Aa]uthored-[Bb]y.*Claude\|Co-[Aa]uthored-[Bb]y.*Copilot")

if [ -z "$COMMITS_WITH_AI" ]; then
    echo "✅ No AI co-authors found in commit history!"
    exit 0
fi

echo "Found $(echo "$COMMITS_WITH_AI" | wc -l) commits with AI co-authors"
echo ""
echo "🔧 Cleaning commit messages..."

# Create a filter script
cat > /tmp/filter-ai.sh << 'EOF'
#!/bin/bash
# Remove AI co-author lines from commit messages
sed \
    -e '/Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d' \
    -e '/Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d' \
    -e '/Co-[Aa]uthored-[Bb]y:.*anthropic/d' \
    -e '/Co-[Aa]uthored-[Bb]y:.*github-actions/d' \
    -e '/Co-[Aa]uthored-[Bb]y:.*\[bot\]/d' \
    -e '/Generated with.*Claude/d' \
    -e '/Generated by.*Copilot/d' \
    -e '/🤖.*Generated/d'
EOF
chmod +x /tmp/filter-ai.sh

# Use git filter-branch to clean history
echo "⏳ Rewriting history (this may take a while)..."
git filter-branch --force --msg-filter '/tmp/filter-ai.sh' \
    --tag-name-filter cat -- --all

# Clean up
rm -f /tmp/filter-ai.sh

echo ""
echo "✅ AI contributors removed from history!"
echo ""
echo "📊 New contributor list:"
git shortlog -sne | head -10

echo ""
echo "⚠️  IMPORTANT NEXT STEPS:"
echo "1. Force push to all remotes: git push --force --all"
echo "2. Force push tags: git push --force --tags"
echo "3. All team members must re-clone or reset their local repos"
echo ""
echo "To update existing clones:"
echo "  git fetch --all"
echo "  git reset --hard origin/main"
echo ""
echo "🎉 Done!"