#!/bin/bash
# Azure DevOps Command Aliases Setup
# Sets up convenient aliases for frequently used Azure DevOps commands

set -e

echo "🔧 Setting up Azure DevOps command aliases..."

# Detect shell
SHELL_RC=""
if [ -n "$ZSH_VERSION" ]; then
    SHELL_RC="$HOME/.zshrc"
    SHELL_TYPE="zsh"
elif [ -n "$BASH_VERSION" ]; then
    SHELL_RC="$HOME/.bashrc"
    SHELL_TYPE="bash"
else
    echo "⚠️ Unsupported shell. Please manually add aliases."
    exit 1
fi

# Create aliases file
ALIASES_FILE="$HOME/.azure-devops-aliases"

cat > "$ALIASES_FILE" << 'EOF'
# Azure DevOps Command Aliases
# Generated by ClaudeAutoPM

# Quick access to daily workflow
alias az-daily='./autopm/.claude/scripts/azure/daily.sh'
alias azd='az-daily'

# Task management
alias az-next='./autopm/.claude/scripts/azure/next-task.sh'
alias azn='az-next'
alias az-tasks='./autopm/.claude/scripts/azure/active-work.sh'
alias azt='az-tasks'
alias az-blocked='./autopm/.claude/scripts/azure/blocked.sh'
alias azb='az-blocked'

# User Story management
alias az-us='./autopm/.claude/scripts/azure/us-list.sh'
alias azu='az-us'
alias az-us-status='./autopm/.claude/scripts/azure/us-status.sh'
alias azus='az-us-status'

# Feature management
alias az-features='./autopm/.claude/scripts/azure/feature-list.sh'
alias azf='az-features'
alias az-feature-show='./autopm/.claude/scripts/azure/feature-show.sh'
alias azfs='az-feature-show'

# Sprint and reporting
alias az-sprint='./autopm/.claude/scripts/azure/sprint-report.sh current'
alias azs='az-sprint'
alias az-dash='./autopm/.claude/scripts/azure/dashboard.sh'
alias azdb='az-dash'

# Synchronization
alias az-sync='./autopm/.claude/scripts/azure/sync.sh --quick'
alias az-sync-full='./autopm/.claude/scripts/azure/sync.sh --full'
alias azsy='az-sync'

# Search
alias az-search='./autopm/.claude/scripts/azure/search.sh'
alias azsr='az-search'

# Validation
alias az-validate='./autopm/.claude/scripts/azure/validate.sh'
alias azv='az-validate'

# Compound commands for common workflows
alias az-morning='az-sync && az-daily && az-sprint'
alias az-standup='az-daily --standup'
alias az-my-work='az-tasks --user=me'
alias az-my-stories='az-us --assigned-to=me'

# Functions for more complex operations
az-work-on() {
    if [ -z "$1" ]; then
        echo "Usage: az-work-on <work-item-id>"
        return 1
    fi
    echo "🚀 Starting work on item #$1..."
    ./autopm/.claude/scripts/azure/task-start.sh "$1"
}

az-complete() {
    if [ -z "$1" ]; then
        echo "Usage: az-complete <work-item-id>"
        return 1
    fi
    echo "✅ Completing work on item #$1..."
    ./autopm/.claude/scripts/azure/task-close.sh "$1"
}

az-find() {
    if [ -z "$1" ]; then
        echo "Usage: az-find <search-term>"
        return 1
    fi
    ./autopm/.claude/scripts/azure/search.sh "$@"
}

az-show() {
    if [ -z "$1" ]; then
        echo "Usage: az-show <work-item-id>"
        return 1
    fi
    # Determine type and show appropriate details
    if [[ "$1" =~ ^F ]]; then
        ./autopm/.claude/scripts/azure/feature-show.sh "$1"
    elif [[ "$1" =~ ^US ]]; then
        ./autopm/.claude/scripts/azure/us-status.sh "$1"
    else
        ./autopm/.claude/scripts/azure/task-show.sh "$1"
    fi
}

# Help function
az-help() {
    echo "📚 Azure DevOps CLI Aliases"
    echo "=========================="
    echo ""
    echo "Daily Workflow:"
    echo "  azd, az-daily      - Daily workflow automation"
    echo "  azn, az-next       - Get next task recommendation"
    echo "  azt, az-tasks      - Show active work items"
    echo "  azb, az-blocked    - View blocked items"
    echo ""
    echo "User Stories:"
    echo "  azu, az-us         - List user stories"
    echo "  azus, az-us-status - Show story status"
    echo ""
    echo "Features:"
    echo "  azf, az-features   - List all features"
    echo "  azfs               - Show feature details"
    echo ""
    echo "Sprint & Reports:"
    echo "  azs, az-sprint     - Sprint report"
    echo "  azdb, az-dash      - Dashboard overview"
    echo ""
    echo "Other:"
    echo "  azsy, az-sync      - Quick sync"
    echo "  azsr, az-search    - Search work items"
    echo "  azv, az-validate   - Validate work items"
    echo ""
    echo "Workflows:"
    echo "  az-morning         - Morning routine"
    echo "  az-standup         - Standup report"
    echo "  az-my-work         - Your active items"
    echo ""
    echo "Functions:"
    echo "  az-work-on <id>    - Start work on item"
    echo "  az-complete <id>   - Complete work item"
    echo "  az-find <term>     - Search for items"
    echo "  az-show <id>       - Show item details"
}

echo "✅ Azure DevOps aliases loaded!"
EOF

# Check if aliases are already sourced
if ! grep -q ".azure-devops-aliases" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# Azure DevOps Command Aliases" >> "$SHELL_RC"
    echo "[ -f ~/.azure-devops-aliases ] && source ~/.azure-devops-aliases" >> "$SHELL_RC"
    echo "✅ Added aliases to $SHELL_RC"
else
    echo "✓ Aliases already configured in $SHELL_RC"
fi

# Set up completions
COMPLETION_FILE="completions/azure-completion.$SHELL_TYPE"
if [ -f "$COMPLETION_FILE" ]; then
    COMPLETION_DEST="$HOME/.azure-devops-completion"
    cp "$COMPLETION_FILE" "$COMPLETION_DEST"

    if ! grep -q ".azure-devops-completion" "$SHELL_RC" 2>/dev/null; then
        echo "[ -f ~/.azure-devops-completion ] && source ~/.azure-devops-completion" >> "$SHELL_RC"
        echo "✅ Added completions to $SHELL_RC"
    else
        echo "✓ Completions already configured"
    fi
fi

echo ""
echo "📋 Installation complete!"
echo ""
echo "To use the new aliases, either:"
echo "  1. Restart your terminal"
echo "  2. Run: source $SHELL_RC"
echo ""
echo "Type 'az-help' to see all available aliases"
echo ""
echo "Quick start commands:"
echo "  azd    - Daily workflow"
echo "  azn    - Next task"
echo "  azt    - Active tasks"
echo "  azs    - Sprint report"
echo "  azdb   - Dashboard"