name: Selective CI/CD Tests

on:
  push:
    branches:
      - main
      - master
      - release/*
  pull_request:
    types: [opened, reopened]
    # Only run on PR if explicitly requested via label
    if: contains(github.event.pull_request.labels.*.name, 'run-tests')
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'quick'
        type: choice
        options:
          - quick
          - full
          - security
          - regression

# Cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Quick tests for regular commits
  quick-tests:
    name: Quick Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.test_suite == 'quick'
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Security Tests
        run: npm run test:security

      - name: Run Regression Tests
        run: npm run test:regression

  # Full test suite - only on main branch or manual trigger
  full-tests:
    name: Full Test Suite
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      github.event.inputs.test_suite == 'full'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run All Tests
        run: npm run test:all

  # Security-only tests
  security-tests:
    name: Security Tests Only
    runs-on: ubuntu-latest
    if: github.event.inputs.test_suite == 'security'
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Security Tests
        run: npm run test:security

  # Local test reminder
  local-test-reminder:
    name: Local Test Reminder
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'run-tests')

    steps:
      - name: Add Comment
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 📝 Local Testing Required

            This PR does not have the \`run-tests\` label, so CI tests won't run automatically.

            Please ensure you've run tests locally before merging:
            \`\`\`bash
            # Quick tests
            ./scripts/local-test-runner.sh --quick

            # Full test suite
            ./scripts/local-test-runner.sh
            \`\`\`

            To trigger CI tests, add the \`run-tests\` label to this PR.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });