name: Validate Contributors

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  check-ai-contributors:
    name: Check for AI Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Check for AI co-authors in commits
        run: |
          echo "🔍 Checking for AI contributors in commit history..."

          # Get all commits in this PR or push
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            COMMITS=$(git log --format='%H' origin/${{ github.base_ref }}..${{ github.sha }})
          else
            COMMITS=$(git log --format='%H' -n 20)
          fi

          FOUND_AI=false

          for commit in $COMMITS; do
            MESSAGE=$(git show -s --format='%B' $commit)

            # Check for AI co-authors
            if echo "$MESSAGE" | grep -iE "Co-[Aa]uthored-[Bb]y:.*(Claude|Copilot|anthropic|github-actions)" > /dev/null; then
              echo "❌ Found AI contributor in commit $commit"
              echo "$MESSAGE" | grep -iE "Co-[Aa]uthored-[Bb]y:.*(Claude|Copilot|anthropic|github-actions)"
              FOUND_AI=true
            fi

            # Check for AI generation mentions
            if echo "$MESSAGE" | grep -iE "(Generated with|Generated by).*(Claude|Copilot)" > /dev/null; then
              echo "❌ Found AI generation mention in commit $commit"
              echo "$MESSAGE" | grep -iE "(Generated with|Generated by).*(Claude|Copilot)"
              FOUND_AI=true
            fi
          done

          if [ "$FOUND_AI" = true ]; then
            echo ""
            echo "⚠️ ERROR: AI assistants found as contributors!"
            echo "AI tools (Claude, Copilot, etc.) must not be listed as contributors."
            echo "Please remove Co-Authored-By lines for AI assistants from commits."
            echo ""
            echo "To fix this:"
            echo "1. Use 'git rebase -i' to edit commit messages"
            echo "2. Remove any Co-Authored-By lines mentioning Claude, Copilot, etc."
            echo "3. Remove any 'Generated with/by' mentions of AI tools"
            exit 1
          else
            echo "✅ No AI contributors found - all commits are clean!"
          fi

      - name: Validate .mailmap doesn't include AI
        run: |
          if [ -f .mailmap ]; then
            echo "🔍 Checking .mailmap for AI entries..."

            if grep -iE "(Claude|Copilot|anthropic|github-actions)" .mailmap > /dev/null; then
              echo "❌ Found AI assistant in .mailmap!"
              grep -iE "(Claude|Copilot|anthropic|github-actions)" .mailmap
              exit 1
            else
              echo "✅ .mailmap is clean!"
            fi
          else
            echo "ℹ️ No .mailmap file found (this is fine)"
          fi

      - name: Check CONTRIBUTORS file
        run: |
          if [ -f CONTRIBUTORS ] || [ -f CONTRIBUTORS.md ] || [ -f AUTHORS ]; then
            echo "🔍 Checking contributor files..."

            for file in CONTRIBUTORS CONTRIBUTORS.md AUTHORS; do
              if [ -f $file ]; then
                if grep -iE "(Claude|Copilot|anthropic|github-actions|\[bot\])" $file > /dev/null; then
                  echo "❌ Found AI assistant in $file!"
                  grep -iE "(Claude|Copilot|anthropic|github-actions|\[bot\])" $file
                  exit 1
                fi
              fi
            done

            echo "✅ Contributor files are clean!"
          else
            echo "ℹ️ No contributor files found (this is fine)"
          fi